import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Link, useLocation } from 'react-router-dom';
import { navItems } from '../utils/nav';
const BottomNav = () => {
    const { pathname } = useLocation();
    return (_jsx("nav", { className: "fixed inset-x-0 bottom-0 z-40 flex items-center justify-around border-t border-gray-200 bg-white/95 px-4 py-3 shadow-soft md:hidden", children: navItems.map((item) => (_jsxs(Link, { to: item.path, className: `flex flex-col items-center text-xs font-medium ${pathname === item.path ? 'text-accent' : 'text-gray-500'}`, children: [_jsx("span", { "aria-hidden": true, className: "text-lg", children: item.icon }), item.label] }, item.path))) }));
};
const SideNav = () => {
    const { pathname } = useLocation();
    return (_jsxs("aside", { className: "hidden w-56 shrink-0 border-r border-gray-200 bg-white/80 px-4 py-6 backdrop-blur md:block", children: [_jsxs("div", { className: "mb-8 flex items-center gap-3", children: [_jsx("div", { className: "flex h-11 w-11 items-center justify-center rounded-xl bg-ink text-white font-semibold shadow-soft", children: "IN" }), _jsxs("div", { children: [_jsx("p", { className: "text-xs text-gray-500", children: "Offline-first" }), _jsx("p", { className: "text-lg font-semibold", children: "Invoice PWA" })] })] }), _jsx("nav", { className: "space-y-2", children: navItems.map((item) => (_jsxs(Link, { to: item.path, className: `flex items-center gap-3 rounded-xl px-3 py-2 text-sm font-medium transition ${pathname === item.path ? 'bg-accent/10 text-accent' : 'text-gray-600 hover:bg-gray-100'}`, children: [_jsx("span", { "aria-hidden": true, className: "text-lg", children: item.icon }), item.label] }, item.path))) })] }));
};
export const AppLayout = ({ children }) => {
    return (_jsxs("div", { className: "min-h-screen bg-surface text-ink md:flex", children: [_jsx(SideNav, {}), _jsxs("div", { className: "flex-1", children: [_jsx("header", { className: "sticky top-0 z-30 border-b border-gray-200 bg-white/80 backdrop-blur", children: _jsxs("div", { className: "mx-auto flex items-center justify-between px-4 py-4 md:px-8", children: [_jsxs("div", { className: "flex items-center gap-3 md:hidden", children: [_jsx("div", { className: "flex h-10 w-10 items-center justify-center rounded-xl bg-ink text-white font-semibold shadow-soft", children: "IN" }), _jsxs("div", { children: [_jsx("p", { className: "text-xs text-gray-500", children: "Offline-first" }), _jsx("p", { className: "text-lg font-semibold", children: "Invoice PWA" })] })] }), _jsx("div", { className: "text-xs text-gray-500 md:text-sm", children: "Foundation layout \u2022 routing ready" })] }) }), _jsx("main", { className: "mx-auto max-w-5xl px-4 py-8 md:px-10 lg:px-12", children: children })] }), _jsx(BottomNav, {})] }));
};
